In [121]:
import pandas as pd

df = pd.read_csv(r"C:\Users\Asus\Desktop\dmdws\pima-indians-diabetes.csv")

In [123]:
df   #display datas

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age,Outcome
0,6,148.0,72,35,0,33.6,0.627,50,1
1,1,85.0,66,29,0,26.6,0.351,31,0
2,8,183.0,64,0,0,23.3,0.672,32,1
3,1,89.0,66,23,94,NaN,0.167,21,0
4,0,137.0,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101.0,76,48,180,32.9,0.171,63,0
764,2,122.0,70,27,0,36.8,0.340,27,0
765,5,121.0,72,23,112,26.2,0.245,30,0
766,1,126.0,60,0,0,30.1,0.349,47,1
767,1,93.0,70,31,0,30.4,0.315,23,0

In [125]:
df.describe()

,Number of times pregnant,Plasma glucose concentration a 2 hours in an oral glucose tolerance test,Diastolic blood pressure (mm Hg),Triceps skin fold thickness (mm),2-Hour serum insulin (mu U/ml),Body mass index (weight in kg/(height in m)^2),Diabetes pedigree function,Age,Outcome
count,768.000000,765.000000,768.000000,768.000000,768.000000,766.000000,768.000000,768.000000,768.000000
mean,3.845052,120.841830,69.105469,20.536458,79.799479,31.993211,0.471876,33.240885,0.348958
std,3.369578,31.903607,19.355807,15.952218,115.244002,7.892244,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.000000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

In [29]:
print(df.head(3));

   Number of times pregnant  \
0                         6
1                         1
2                         8

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                148
1                                                 85
2                                                183

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                72                                35
1                                66                                29
2                                64                                 0

   2-Hour serum insulin (mu U/ml)  \
0                               0
1                               0
2                               0

   Body mass index (weight in kg/(height in m)^2)  Diabetes pedigree function  \
0                                            33.6                       0.627
1                                            26.6                       0.351
2                                            23.3                       0.672

   Age  Outcome
0   50        1
1   31        0
2   32        1

In [31]:
print(df.tail(3));

     Number of times pregnant  \
765                         5
766                         1
767                         1

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
765                                                121
766                                                126
767                                                 93

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
765                                72                                23
766                                60                                 0
767                                70                                31

     2-Hour serum insulin (mu U/ml)  \
765                             112
766                               0
767                               0

     Body mass index (weight in kg/(height in m)^2)  \
765                                            26.2
766                                            30.1
767                                            30.4

     Diabetes pedigree function  Age  Outcome
765                       0.245   30        0
766                       0.349   47        1
767                       0.315   23        0

In [35]:
print(df.dtypes)   #print datatypes of the given datas

Number of times pregnant                                                      int64
Plasma glucose concentration a 2 hours in an oral glucose tolerance test      int64
Diastolic blood pressure (mm Hg)                                              int64
Triceps skin fold thickness (mm)                                              int64
2-Hour serum insulin (mu U/ml)                                                int64
Body mass index (weight in kg/(height in m)^2)                              float64
Diabetes pedigree function                                                  float64
Age                                                                           int64
Outcome                                                                       int64
dtype: object

In [131]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:\Users\Asus\Desktop\dmdws\pima-indians-diabetes.csv")

# Check for missing values
missing_values = df.isnull().sum()

# Display missing values per column
print("Missing values in each column:\n", missing_values)

Missing values in each column:
 Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    3
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index (weight in kg/(height in m)^2)                              2
Diabetes pedigree function                                                  0
Age                                                                         0
Outcome                                                                     0
dtype: int64

In [51]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:\Users\Asus\Desktop\dmdws\pima-indians-diabetes.csv")

# Add a new column
df["New_Column"] = 0  

# Display updated Data
print(df.head())

   Number of times pregnant  \
0                         6
1                         1
2                         8
3                         1
4                         0

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                                148
1                                                 85
2                                                183
3                                                 89
4                                                137

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                72                                35
1                                66                                29
2                                64                                 0
3                                66                                23
4                                40                                35

   2-Hour serum insulin (mu U/ml)  \
0                               0
1                               0
2                               0
3                              94
4                             168

   Body mass index (weight in kg/(height in m)^2)  Diabetes pedigree function  \
0                                            33.6                       0.627
1                                            26.6                       0.351
2                                            23.3                       0.672
3                                            28.1                       0.167
4                                            43.1                       2.288

   Age  Outcome  New_Column
0   50        1           0
1   31        0           0
2   32        1           0
3   21        0           0
4   33        1           0

In [129]:
import pandas as pd
import numpy as np

# Load dataset
df = pd.read_csv(r"C:\Users\Asus\Desktop\dmdws\pima-indians-diabetes.csv")

# Add a new column with a value
df["Health_Status"] = "Unknown" 

# Display updated Data
print(df.head())

   Number of times pregnant  \
0                         6
1                         1
2                         8
3                         1
4                         0

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                              148.0
1                                               85.0
2                                              183.0
3                                               89.0
4                                              137.0

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                72                                35
1                                66                                29
2                                64                                 0
3                                66                                23
4                                40                                35

   2-Hour serum insulin (mu U/ml)  \
0                               0
1                               0
2                               0
3                              94
4                             168

   Body mass index (weight in kg/(height in m)^2)  Diabetes pedigree function  \
0                                            33.6                       0.627
1                                            26.6                       0.351
2                                            23.3                       0.672
3                                             NaN                       0.167
4                                            43.1                       2.288

   Age  Outcome Health_Status
0   50        1       Unknown
1   31        0       Unknown
2   32        1       Unknown
3   21        0       Unknown
4   33        1       Unknown

In [80]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:\Users\Asus\Desktop\dmdws\pima-indians-diabetes.csv")

# Create a new row
new_row = pd.DataFrame([{
    'Number of times pregnant': 3,
    'Plasma glucose concentration a 2 hours in an oral glucose tolerance test': 130,
    'Diastolic blood pressure (mm Hg)': 75,
    'Triceps skin fold thickness (mm)': 20,
    '2-Hour serum insulin (mu U/ml)': 85,
    'Body mass index (weight in kg/(height in m)^2)': 26.5,
    'Diabetes pedigree function': 0.6,
    'Age': 29,
    'Outcome': 0 
}])

# Use pd.concat() to add a new row
df = pd.concat([df, new_row], ignore_index=True)

# Display the updated Data
print(df.tail())  # Show the last few rows to confirm the new row is added

     Number of times pregnant  \
764                         2
765                         5
766                         1
767                         1
768                         3

     Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
764                                                122
765                                                121
766                                                126
767                                                 93
768                                                130

     Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
764                                70                                27
765                                72                                23
766                                60                                 0
767                                70                                31
768                                75                                20

     2-Hour serum insulin (mu U/ml)  \
764                               0
765                             112
766                               0
767                               0
768                              85

     Body mass index (weight in kg/(height in m)^2)  \
764                                            36.8
765                                            26.2
766                                            30.1
767                                            30.4
768                                            26.5

     Diabetes pedigree function  Age  Outcome
764                       0.340   27        0
765                       0.245   30        0
766                       0.349   47        1
767                       0.315   23        0
768                       0.600   29        0

In [82]:
value = df.iloc[344, 1]  # Row index, Column index extracting
print(value)

95

In [133]:
import pandas as pd

# Load dataset
df = pd.read_csv(r"C:\Users\Asus\Desktop\dmdws\pima-indians-diabetes.csv")

# missing values before filling
print("Missing values before filling:\n", df.isnull().sum())

# Fill missing values with mean
df.fillna(df.mean(numeric_only=True), inplace=True)

# missing values after filling
print("\nMissing values after filling:\n", df.isnull().sum())

# Display first few rows of the updated dataset
print("\nUpdated DataFrame:\n", df.head())

Missing values before filling:
 Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    3
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index (weight in kg/(height in m)^2)                              2
Diabetes pedigree function                                                  0
Age                                                                         0
Outcome                                                                     0
dtype: int64

Missing values after filling:
 Number of times pregnant                                                    0
Plasma glucose concentration a 2 hours in an oral glucose tolerance test    0
Diastolic blood pressure (mm Hg)                                            0
Triceps skin fold thickness (mm)                                            0
2-Hour serum insulin (mu U/ml)                                              0
Body mass index (weight in kg/(height in m)^2)                              0
Diabetes pedigree function                                                  0
Age                                                                         0
Outcome                                                                     0
dtype: int64

Updated DataFrame:
    Number of times pregnant  \
0                         6
1                         1
2                         8
3                         1
4                         0

   Plasma glucose concentration a 2 hours in an oral glucose tolerance test  \
0                                              148.0
1                                               85.0
2                                              183.0
3                                               89.0
4                                              137.0

   Diastolic blood pressure (mm Hg)  Triceps skin fold thickness (mm)  \
0                                72                                35
1                                66                                29
2                                64                                 0
3                                66                                23
4                                40                                35

   2-Hour serum insulin (mu U/ml)  \
0                               0
1                               0
2                               0
3                              94
4                             168

   Body mass index (weight in kg/(height in m)^2)  Diabetes pedigree function  \
0                                       33.600000                       0.627
1                                       26.600000                       0.351
2                                       23.300000                       0.672
3                                       31.993211                       0.167
4                                       43.100000                       2.288

   Age  Outcome
0   50        1
1   31        0
2   32        1
3   21        0
4   33        1